services:
  app:
    build: .
    container_name: lombardo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lombardodb
      - SPRING_DATASOURCE_USERNAME=lombardo
      - SPRING_DATASOURCE_PASSWORD=lombardo

  db:
    image: postgres:latest
    container_name: lombard-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lombardodb
      - POSTGRES_USER=lombardo
      - POSTGRES_PASSWORD=lombardo
    volumes:
      - lombardo-db:/var/lib/postgresql/data

volumes:
  lombardo-db:

